version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: encryptionApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: garaali
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  encryptionApp:
    image: garaali/encryption_app_be:1.0.0
    container_name: encryptionApp
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/encryptionApp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=garaali
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
